# Generated by Django 4.1.3 on 2023-06-23 20:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0006_delete_photo'),
        ('comandas', '0003_alter_comanda_status_alter_comanda_valortotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('cod', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('status', models.IntegerField(default=0)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('comanda', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='comandas.comanda')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_Produto',
            fields=[
                ('cod', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('cod_pedido', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('cod_produto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
    ]
