# Generated by Django 4.2.2 on 2023-06-16 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('comandas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('cod', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.CharField(max_length=200)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comandas.comanda')),
                ('produtos', models.ManyToManyField(related_name='Produtos', to='produtos.produto')),
            ],
        ),
    ]
