# Generated by Django 4.1.3 on 2023-06-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
