# Generated by Django 4.1.3 on 2023-07-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_data_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='data_hora',
        ),
    ]
