# Generated by Django 4.1.3 on 2023-06-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
