# Generated by Django 4.2.2 on 2023-07-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_pedido_data_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='opcaoPagamento',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='trocoPara',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
