# Generated by Django 4.2.2 on 2023-07-07 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_opcaopagamento_pedido_trocopara'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='opcaoPagamento',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='trocoPara',
        ),
    ]
