# Generated by Django 4.1.3 on 2023-06-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_remove_pedido_produtos_pedido_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_produto',
            name='quantidade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
