# Generated by Django 4.2.2 on 2023-06-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('cod', models.BigAutoField(primary_key=True, serialize=False)),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mesa', models.IntegerField()),
            ],
        ),
    ]
