# Generated by Django 4.1.3 on 2023-06-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0002_comanda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='valorTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
