# Generated by Django 4.1.3 on 2023-07-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0003_alter_comanda_status_alter_comanda_valortotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='dataCriacao',
            field=models.DateTimeField(default='2023-07-05 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comanda',
            name='dataFechamento',
            field=models.DateTimeField(default='2023-07-05 12:00:00'),
            preserve_default=False,
        ),
    ]
