# Generated by Django 4.2.2 on 2023-07-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0005_rename_datacriacao_comanda_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateTimeField(blank=True),
        ),
    ]
