# Generated by Django 4.2.2 on 2023-07-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0006_alter_comanda_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='data',
        ),
    ]
