# Generated by Django 4.2.2 on 2023-07-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0007_remove_comanda_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='opcaoPagamento',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='comanda',
            name='trocoPara',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
