# Generated by Django 4.2.2 on 2023-07-10 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0009_comanda_data_e_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comanda',
            old_name='trocoPara',
            new_name='troco',
        ),
    ]
