# Generated by Django 4.1.3 on 2023-06-15 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comanda', '0001_initial'),
        ('Pedido', '0002_alter_pedido_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comanda',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Comanda.comanda'),
            preserve_default=False,
        ),
    ]
