# Generated by Django 4.1.3 on 2023-06-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='valorUnitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
