# Generated by Django 4.1.3 on 2023-06-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_estoque_alter_produto_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='img',
            field=models.ImageField(default=1, upload_to='', verbose_name='img'),
            preserve_default=False,
        ),
    ]
