# Generated by Django 4.1.3 on 2023-06-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_produto_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
