# Generated by Django 4.1.3 on 2023-06-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('cod', models.BigAutoField(primary_key=True, serialize=False)),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mesa', models.IntegerField()),
            ],
        ),
    ]
