# Generated by Django 4.1.3 on 2023-07-01 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='tipo',
        ),
    ]
